# Generated by Django 3.0.1 on 2020-08-02 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
