# Generated by Django 3.0.1 on 2020-08-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addshg', '0005_shg_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shg',
            name='phno',
            field=models.BigIntegerField(default=0, max_length=10),
        ),
    ]
