# Generated by Django 3.0.1 on 2020-08-02 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addshg', '0007_auto_20200801_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='InstallDueDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='Score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='shg',
            name='InstallDueDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
