# Generated by Django 3.0.1 on 2020-08-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addshg', '0009_auto_20200802_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanregister',
            name='Score',
        ),
        migrations.AddField(
            model_name='shg',
            name='Score',
            field=models.IntegerField(default=10),
        ),
    ]
