# Generated by Django 3.0.1 on 2020-08-03 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addshg', '0010_auto_20200802_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='shg',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
